dependencies:
  - aave/protocol-v2@1.0.1
compiler:
  solc:
    remappings:
      - "@aave=aave/protocol-v2@1.0.1"
dotenv: .env
networks:
  kovan:
    weth_token: "0x87b1f4cf9bd63f7bbd3ee1ad04e8f52540349347"
  mainnet-fork:
    weth_token: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
wallets:
  from_key: ${PRIVATE_KEY}
