dependencies:
  - aave/protocol-v2@1.0.1
compiler:
  solc:
    remappings:
      - "@aave=aave/protocol-v2@1.0.1"
dotenv: .env
networks:
  default: mainnet-fork
  kovan:
    weth_token: "0x87b1f4cf9bd63f7bbd3ee1ad04e8f52540349347"
    lending_pool_addresses_provider: "0x88757f2f99175387ab4c6a4b3067c77a695b0349"
  mainnet-fork:
    weth_token: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
    lending_pool_addresses_provider: "0xB53C1a33016B2DC2fF3653530bfF1848a515c8c5"
wallets:
  from_key: ${PRIVATE_KEY}
