dependencies:
  # <organization/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1"
  dotenv: .env
  networks:
    kovan:
      eth_usd_price_feed: "0x504bebA34f5541cE408BF93AbF5522c873a770EA"
      verify: True
    development:
      verify: False
  wallets:
    from_key: ${PRIVATE_KEY}
